### ISSUE TITLE
Missing `main` entry

### ISSUE THREAD

**Issue by yeya** [rx-ts/rollup#71]
After upgrading to 1.3.0 from 1.1.0 I can't use this plugin with grunt. Rolling back to 1.1.0 fixed it.
```
Cannot find module '....\node_modules\rollup-plugin-insert\lib\cjs'.
Please verify that the package.json has a valid "main" entry
```

**Comment by JounQin** [comment]
Thanks for your reporting, it should be fixed in v1.3.1.
